{
  "hash": "8644edb2ec6cf10eae2c3bcaf18571d0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A Holiday Storm: 2003\"\nauthor: \"DK\"\ndate: \"2025-12-28\"\nexecute: \n  echo: false\ncategories: [storms]\n---\n\n\n\nAs if to spur or seed the moisture that has been lacking in the valleys and mountains this year, local media recently ran this headline **\"Remembering Utah's Epic Snowstorms.\"**^[https://www.ksl.com/article/51421062/remembering-utahs-epic-snowstorms-heres-the-top-6-that-made-history]\n\nFor those of us who live along the Wasatch Range, snow is more than just weather; it is a shared history.\n\nThe article provided a list of the single greatest 24-hour accumulations in recent history:\n\n|                  |                           |\n|------------------|---------------------------|\n| **Month-Year**   | **Amount in Inches (cm)** |\n| October 1984     | 18.4 (46.7)               |\n| December 2003    | 19.4 (49.3)               |\n| January 1996     | 19.8 (50.3)               |\n| February 1998    | 20.4 (51.8)               |\n| March 1944       | 21.6 (54.9)               |\n| **January 1993** | **23.3 (59.2)**           |\n\nThe article concluded with a staggering figure:\n\n**50.3 inches (127.8 cm)** fell in total during that single month of January 1993—the most on record in Utah’s history.\n\nThe author then invited readers to \"share your memories of Utah's greatest snowstorms.\"\n\nAs I scanned the list, I realized that except for the 1944 storm, I was in town for every single one of them.\n\n------------------------------------------------------------------------\n\nWe moved into the Indian Hills area of Provo in December 1992.\n\nIt was our first home, that nearly doubled our living space compared to the student housing we had occupied for the previous three years.\n\nI remember the warmth of the community—neighbors welcoming us by caroling on our front porch.\n\nThen, about two weeks later, the sky opened up.\n\nThe great snowstorm began on January 5th.\n\nAccording to the records, it snowed for twenty-two hours straight, leaving 23.3 inches (59.2 cm) on the ground in a single day.\n\nBut the storm was just the beginning; the snow kept coming throughout the month.\n\nBy the time January came to a close, the totals had climbed to a staggering 50.3 inches (127.8 cm).\n\nThere were reports of people climbing—and inevitably falling off—their roofs in an attempt to clear the mounting weight.\n\nAs a first-year homeowner, I was paralyzed by a lack of experience. I had no basis for comparison and no idea if my roof was in danger or if I should climb the roof.\n\nI took no action.\n\nIn that instance, the indecision of not knowing what to do probably saved my life—or at least my back.\n\n------------------------------------------------------------------------\n\nThese photos are not from 1993 or 2004.\n\n------------------------------------------------------------------------\n\n![](images/IMG_7737.JPG)\n\n![](images/2005NewYearPrayer&Party019.JPG)\n\n![](images/DSC01083.JPG)\n\nIn those years, before regular airline service was common, our trips to Phoenix were always measured in highway miles.\n\nWe had general plans for our Christmas visit in 2004, but we hadn’t settled on a departure date—until we saw the weather map.\n\nRealizing we needed to outrun a massive incoming front, we made the sudden decision to depart on Christmas Eve.\n\nFor the first few hours, our choice seemed correct. But as we reached Buckskin Valley on Utah Road 20—the high-altitude artery connecting Panguitch to I-15—the storm finally caught us.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"leaflet html-widget html-fill-item\" id=\"htmlwidget-ce921eebc52a190d3088\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-ce921eebc52a190d3088\">{\"x\":{\"options\":{\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}}},\"calls\":[{\"method\":\"addProviderTiles\",\"args\":[\"OpenStreetMap\",null,null,{\"errorTileUrl\":\"\",\"noWrap\":false,\"detectRetina\":false}]},{\"method\":\"addMarkers\",\"args\":[38.03401190428473,-112.5334079474563,null,null,null,{\"interactive\":true,\"draggable\":false,\"keyboard\":true,\"title\":\"\",\"alt\":\"\",\"zIndexOffset\":0,\"opacity\":1,\"riseOnHover\":false,\"riseOffset\":250},\"Project Location\",null,null,null,null,{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},null]}],\"setView\":[[38.03401190428473,-112.5334079474563],12,[]],\"limits\":{\"lat\":[38.03401190428473,38.03401190428473],\"lng\":[-112.5334079474563,-112.5334079474563]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\nAt the summit, visibility vanished.\n\nMy headlights hit the driving flakes, transforming the world into a shimmering, impenetrable white curtain.\n\nDescending the steep, hairpin turns of the downgrade became a terrifying driving lesson I hope never to repeat.\n\nI said many prayers throughout those endless, winding miles, my hands white-knuckled on the wheel.\n\nWe eventually reached US-89, and as the terrain flattened out, we pushed forward until we reached the safety of Kanab.\n\nEven after we finally lay down to sleep, the image of that white blanket remained burned into my vision.\n\nI attribute our survival that night to a brand-new set of Michelin tires and a great deal of help from above.\n\nIt took me a while to recover from that ordeal.\n\n------------------------------------------------------------------------\n\nDuring the January 1993 storm, inaction saved me from harm.\n\nHowever in 2004 Christmas storm, my decision to push through the snowstorm may have resulted in making the news for all the wrong reasons.\n\nGrateful that I can remember these snowstorms and draw lessons from them.\n\nAs I look at the mountains today, I find myself hoping that the cycle of epic snow—or something close to it—returns to this part of the West.\n\nWithout the chaos or the life-threatening situations.\n\n![](images/snow patrol 01.jpg)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/leaflet-1.3.1/leaflet.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/leaflet-1.3.1/leaflet.js\"></script>\n<link href=\"../../site_libs/leafletfix-1.0.0/leafletfix.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/proj4-2.6.2/proj4.min.js\"></script>\n<script src=\"../../site_libs/Proj4Leaflet-1.0.1/proj4leaflet.js\"></script>\n<link href=\"../../site_libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/leaflet-binding-2.2.2/leaflet.js\"></script>\n<script src=\"../../site_libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js\"></script>\n<script src=\"../../site_libs/leaflet-providers-plugin-2.2.2/leaflet-providers-plugin.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}