---
title: "Classification"
author: "DK"
date: "2025-09-08"
draft: yes
categories: [potential]
---

Out of curiosity and necessity we label or classify things in life.

Makes it easier to identify, categorize and find proper place.

Likewise, it may be convenient to classify people based on the outward appearance

Or all the things that should not be a reason for comparison.

**race, color, religion, sex, national origin, age (40+), disability, or genetic information.**

all outward appearance, except perhaps religion.

My mother can be categorized as an immigrant from Korea.

But more particularly, she is a refugee from the North.

However, had there been no communism and no civil war.

And if her father lived past 30 years of age, things would have turned out differently.

Much different.

As a land and business owner and an eldest daughter of thriving businessmen, she would be educated and married to a prominent family in the region.

Or they may choose to seek a husband for her from the ancestral home area.

From the 강서군 of 평양

38.91742229169456, 125.52034339069476

As it turned out, Grandpa Hwang passed away at age 36.

When my mother turned 13.

The Soviet Union occupied the Northern part of Korea and exerted communist ideals.

Then when she turned 18 the civil war, known as the Korean War broke out.

At age 19, she fled her home on a hired boat, escaping to 진도섬 some 250 miles to the south.

I don't recall her being bitter about how things turned out.

Nor did she murmur about the new life.

She was 42 when she landed in Washington DC area.

She managed to rebuild her life, as she did 23 years before when she fled North Korea.
