---
title: "Local Events"
author: "DK"
date: "2025-09-07"
draft: yes
categories: [neighborhood]
---

Attended 3 events in 3 hours.

Neighborhood gathering.

Neighborhood wedding

Neighborhood athletic event.

---

Normally the Saturday evening session for adults start at 7PM.

Not this evening, it started at 5:30.

The wedding reception started at 7PM.

Told the Stake Patriarch, who used to be BYU Law School Dean,

> Didn't know the J Family had so much pull. Fact that they can move the Stake Conference schedule.

The former Dean reiterated what many have suspected.

Rather than compete with the BYU Football scheduled for 8:30PM kick-off, the Stake officials moved their schedule.

---

The BYU Athletics is removing all semblance of independent fans.

No bags policy, to further strengthen already ludicrous concession offerings.

Making everyone wear whites.

Might as well copy everything else from the communist rulers.

Made a vow not to attend more athletic events, where I pay, give up my time.

Furthermore, I will not contribute to BYU in any amount.
