---
title: "Classified Labels"
author: "DK"
date: "2025-12-12"
draft: yes
categories: [labels, classifications]
---

Out of necessity we label and classify things.

Much of Western Civilization and its learning is based on classifications.

However, we seemed to have taken this approach to things that should not be classified or labelled.

Because when we label or classify things and people we not only make it more known and manageable but we have limited its potential, its growth and it is no longer mysterious.

> **道可道，非常道。名可名，非常名**

The truth that may be told is not everlasting Truth. The name given to a thing is not the everlasting Name.[^1]

[^1]: https://pages.ucsd.edu/\~dkjordan/chin/LaoJuang/DDJTenTranslations.html

YANG Chia-lo \[Yáng Jiāluò \] **楊家駱**

:   1962 **老子** truth and nature. Hong Kong: **萬國書店**. Pp. 2-3.

------------------------------------------------------------------------

My parents made it seem that we were middle class or even an elite family.

They didn't give us a target or limiting goals.

But they showed us the way or paths to those realms.

Much like how Heavenly Father guides us in this life.

Subtle and effective ways, if we listen and obey.
