---
title: "Bonus Life"
author: "DK"
date: "2025-06-24"
categories: [epoch]
---

Twenty years and 3 months

That was my father's age when the Korean War started 75 years ago.

Many B&W photos taken in Korea were in 자유공원

When my grandmother Kim was born the life expectancy was 25\~35 years.

Mainly due to high infant mortality

She lived to be 92, outliving the estimate by nearly 60 years.

When my parents were born in the 1930s, it was 32.4 years for men and women at 35.1 years

My father lived to 90 and my mother 91.

For me to live comparable what my parents and grandmother achieved.^[life expectancy, when I was born, in Korea was 53.8 years]

I would have to live to be 110 years of age.

---

Both of my parents lived a bonus life.
Both lost 2 of their siblings when they were in infancy

And their fathers died or became AWOL when young
My maternal grandfather passed away from gastro-intestinal disease in mid 30s
My paternal grandfather defected to North Korea.

After surviving the war, both of my parents must have felt that a second life was granted.

They stayed in touch with life but noting would rattle them.
