---
title: "My Life: Mildred Frances Lewis Turley"
subtitle: "Tape 1 - Side B : 14 Dec 1991"
author: "MT"
date: "17 Sep 2025"
draft: yes
categories: [auto-biography]
---

**My Early School Days and Activities**

***This chapter tells you about my elementary school experiences, from learning to read and do basic math, to my teachers, and all the fun we had during recess.***

I remember struggling with reading because I would go too fast. Finally, a teacher told me if I didn't read slowly enough to tell her what I'd read, she would tell Doris to tell my mother I wouldn't be home for lunch. Oh boy, I read it slow enough! I didn't want to miss lunch, so I slowed up and read it, and I told him what was in it. I really did learn how to add, multiply, subtract, and write. Then I went into 4th grade, and that teacher taught me. In 5th grade, my teacher was Mr. Hat, and I liked him. He didn't teach the next year, so my Uncle Charlie Whipple was my teacher in 6th grade, and he was a good teacher too. When I got up into 9th grade, my teacher wasn't very helpful, and I saw one boy being tormented by another student in the class.

School started every morning with a bell on the hill, ringing about half an hour before it was time to go to school. The principal or one of the teachers would ring it. They did the same thing for recess, at lunchtime, and then when it was time to go home at night. At recess, we used to play on the "Giants side". I lost so many shoes riding down it, but I loved to ride down the slide and swings. We would also play baseball. In the wintertime, when it was snowy, we had sleds – they don't have many anymore – but we would take them to school. During recess, we'd slide down the hill; we had more fun falling down that hill on the sled. While some children stayed at school for lunch, I always liked to go home unless it was a really cold and sunny day. I forgot to tell you that in the 2nd grade, I had a cousin, Uncle Archie's daughter, and then Shirley and Obie's Grant, whom we used to play with a lot. We would sometimes squabble and argue. I remember one day, my cousin Sybil fainted in school. I don't know what caused the fainting, but when school was out, I went running home and told my Mama, "Guess what, I got a name here!".

**My High School Years and Personal Trials**

***This chapter covers my transition to high school, a significant injury that impacted my education, and my experiences with seminary classes.***

After I made it through 8th grade, it was time for graduation, and I was just so excited to be graduating to high school. I knew I was going to have a different experience there. I remember our graduation exercises, the dress I wore, and the shoes. I was even allowed to give my office, which I thought was really something. I had a real nice summer, and then it was time to start high school. I can't remember just how long I had been going to school as a freshman, not too long, I don't think.

We had hand water in our house, and I was heating water on the stove for washing up and getting ready for school. The night before, someone had dropped the axe on the floor, and I didn't know it was there. When I went across with the hand water, I stepped on it and split my foot. It was so painful. They didn't have doctors like they do now. I remember my mom and daddy talking about taking me to the hospital, but they never did. So, my foot had been partially broken, and it had to heal on its own. I remember having to learn to walk all over again by pushing a chair. That was so painful; to this day, I don't know how I survived it. I never even had any pain pills or anything. I had hoped to go on to be a sophomore next year, but the principal wouldn't let me. He made me take my freshman year over again.

I took seminary when I was in high school. They had 'release time' classes to go to seminary. I did not like my seminary teacher. I took three years of seminary, and when it got time for us to graduate, he didn't have a diploma for me! I just couldn't believe that, since I had completed my work. But I kept pestering him until he found and got me my diploma. When we went to get our diplomas, I was the only one that didn't get one initially.

**My Post-High School Work and Community Contributions**

***This chapter details my diverse work experiences after high school, the impact of national events like Pearl Harbor, and my significant act of community giving.***

I think it was probably the summer after maybe my sophomore or junior year; I don't remember what year it was, but anyway, my cousin Ellen, who had been living in Taylor, got married in September 1939. We used to go down and visit with them quite a bit. She lived in her own little home. We really did like to go visit with her and stay with her. Then she moved out into the Monthly Ranch, and we would go out there and stay with her also. In 1941, my brother died in January, and my relatives Marbury and Carl were married on July 26th that same year.

Doris and I went down and got a summer job at the Air Force Base in Douglas, where her brother Lester was a fireman. So we went down and spent the summer with him. Doris was a teletype operator, and I worked in what they called the 'wagon apartment'. I would go around selling hot coffee, donuts, popcorn, candy, gum, and other snacks. I remember when I'd go around, I'd say, "Hot coffee! Donuts! Popcorn, candy!" and they would come running. The Japanese bombed Pearl Harbor on December 7, 1941. After that, things had to be rationed; I remember sugar and gas, and quite a few other things. While I was on this summer job, I saved quite a bit of money. I really did enjoy that summer down there. We met many good people, including a boy from Mesa, Arizona, whom I thought was a pretty nice boy. I wanted so badly for him to ask me out.

I graduated from high school in 1947. After I graduated, I started working an all-night shift, but I didn't like it because I had to sleep during the day. Then, Doris and I got a job as waitresses at the Paint Pony Lodge for Mary and Eric. They had a few rooms they rented out, mostly serving people who stayed there, but they also took people off the highway. We quite liked the job; we really made good money there. I remember one evening, four or five people came in. Doris told me, "You can take those people," and she would take her own. So I took their order, and they ordered meals. I realized they must be Mormons and they said, "Yes, I'm Brother John Longdon, and we're down from Salt Lake for a convention". I got to wait on them, and they gave me good tips. I was really glad Doris let me wait on them because I got better tips that way. I would save my money, putting my tips in a jar on my bed every night, and put my check in the bank. I finally got \$100 from that job.

I said to my parents, "What can I do? I wonder if I'd like to do something good". I always paid my tithing. We were building a chapel on the hill for the old troops, and we really needed supplies. I said, "I know what I'm going to do! I'm going to take this \$100 over and give it to Bishop Built for the donations to build the fund". I went over and handed Bishop Built the money, and he emptied the dollars out. I said, "I want you to use it for the building". There was \$100 there, and he just didn't believe I would do that, to donate \$100 to the building. Doris, I think, got mad at me for that, and we quit our job out there.^[\$100 in 1947 is equivalent in purchasing power to about $1,448.65 today.  78 Years and 3.5% inflation rate per year]

My next job was with Wayne Bartlett, and sometimes he wanted me to work on Sundays. I went through a dilemma, praying about whether I should work on Sunday. I finally just decided on my own that I knew my mom didn't want me to work on Sunday, so I told him I wouldn't. Then, my next job was with a German man at a service station.

**The Call to Mission and Pre-Departure Events**

Even though I wanted to get married, I received an exciting mission call, and my family and I made preparations for my journey.

While I still hadn't married, and I wanted to get married so badly, I finally got my mission call! I was so excited that it was to Alberta, Canada. I knew it was going to be cold up there, and I told them they had to build me a different home. *However, one source also states the mission call was to "American Fork, Utah".* As I got ready for my mission, my cousin, who is a genealogist, Paul Lilly, and Doris, helped me. We were in Salt Lake City, and my cousin was proposed to and became engaged to be married in January. I went down to get my mission. They got married in January.

**My Journey and Arrival at Mission**

My journey to the mission was quite eventful, involving a long, uncomfortable train ride and a derailment, before I finally arrived at the mission headquarters.

Dorothy and Herman, who were now engaged, stayed in Salt Lake with me until it was time for my flight into Canada. They didn't fly with me. I got on the train with four other women, and one of these girls was going to the same mission as I was. As the train left Salt Lake, I could still see Doris and Herman waving and standing by, and the more we went, the more homesick I got. I had never left home before. We got up to Montana, and the train derailed, so we had to get off the train. I needed my passport for the Canadian border to get into Canada. We got on another train, but it only had one passenger car, and the rest was very bumpy. The Canadian food was unappetizing; I just couldn't get hungry enough to eat that lunch. With all the bumping around, I kept saying we couldn't ever eat that food.

At nighttime, they put up the berths for us to sleep in. They told us they would get the berths ready, and then they'd come back and let us know. We waited and waited, and finally, we walked up there ourselves, and everybody was in bed and sound asleep. Anyway, we got to the Edmonton Hotel, which was the mission headquarters. When the train stopped, there were two elders waiting for us, one of whom was Elder Ellwood. They picked us up and took us over to the mission home. I hadn't been there very long when the phone rang, and it was Jack McLaughlin from Holbrook, Arizona. I had no idea who he was, but he knew I was coming from Arizona, and Holbrook was where I was supposedly coming from. He called and talked to me, and I really appreciated that; it took away a little bit of the homesickness I felt, even though I didn't know him.

---

## Internet Findings

[Whipple Family Tree](https://yawt.whipple.org/familychart.php?familyID=F5213&tree=whipple)

[Family Search Entry](https://ancestors.familysearch.org/en/KW8V-QW2/mildred-frances-lewis-1928-1996)

[Whipple Photo](https://whipplephoto.com/Genealogy/familygroup.php?familyID=F41137&tree=tree1&sitever=standard)
