---
title: "Level Up"
author: "DK"
date: "2025-10-01"
draft: yes
categories: [remembrance]
---

Koreans help one another during celebrations and in times of sorrow.

부조금(扶助金) or assistance money is given and received to help ease the burden of wedding celebration or to allay or cover funeral expenses.

When my mother passed away, Dad's youngest brother, who lived with us until he was married, about 12 years, sent a large sum of money as 부조금(扶助金).

When we called to thank him and asked why so much.
He said, to repay his debt to her, he should have sent a lot more.

His reasoning was then my mom, elevated his life's standing, or raised his level in the society by educating him.

This was at a time when per capita income was couple hundred dollars.

---

The education arrangement was that, as long as the uncle passed entrance exams, my mom would support him financially.

We have a common saying, "Kangs are good at taking exams"
Instead of saying we are good students.
I suppose one can't be one without the foundation.

One time, money was really tight.
Mom asked the uncle to take time off and serve in the military.
She told him, perhaps by the time he completes his service, things will be better.

This was a time when there was no military draft in Korea.
Thus, to volunteer for the military service was an admission of a dire situation.
My uncle recognizing the severity of the situation, volunteered.

My earliest memory is visiting him with mother.
He was stationed near Pusan, in a place called 김해.
It must have taken mom and a better part of a day to travel 400 to 500 km in those days.

---

That uncle graduated and was married.
Though he was youngest, he took care of grandma for over 30 years, after we left Korea.
As well as taking care of matters that were normally handled by the oldest son.
So my uncle obtained education but he also paid off the tuition by providing much needed service to the family.

Nearly 60 years after my mom housed him and educated him, his words were one of gratitude.

---

Mothers in those days must have had a special talent.
They made us feel that we were not poor but we were blessed and had a great potential to succeed.
And amazingly we all believed we could achieved anything and we were not that poor as statistics would later suggest.

---

I still unsure how she did it.
But here is my guess.

My mother determined that her children would not go through what she went through.
War caused famine and lost opportunity for education.
We would eat high quality food and earn education, even if it meant my parents sacrificing their comfort.

---

So my uncle is correct.
We all benefitted from my mother's sacrifice.
We are all elevated or live a higher level life because of her.








