---
title: "Convenience and Comfort"
author: "DK"
date: "2025-07-21"
draft: yes
categories: [hardship]
---

Traveled to a place where food was fit for Goldilocks.

It wasn't too spicy, too salty, but just right.

Took many photos, they came out better than I expected.

In fact, all of them were technically just right, as algorithm dictated it to be.

Didn't have to make any travel plans.

Hosts took care of it, I just had to be ready and they chauffeured me from places to places using the latest navigation tools.

------------------------------------------------------------------------

Consequently, I didn't get lost nor went to a bad eating establishment.

Then again, I never learned how to figure out directions or where I was visiting.

By looking at metadata on photos, I could retrace places I visited.

In the days past, I would be asking directions even after pouring over maps.

Looking for landmarks, such as banks or natural indicators.

Also consulting the position of the sun to determine the direction in the absence of landmarks.

This approach was mistake-prone but after a day or so, one usually figured out the lay of the land.

Food was not only presented well and flavored ideally, but also there were over abundance of it.

Growing up, food was scarce and meals were served plain with mostly vegetables, fishes and occasional meat enhanced soups.

Food was local and seldom got to taste cuisine from other locations

We tasted meat, a couple times a year, usually during holidays or birthdays of older people.

On a recent trip, we got to sample food from all regions of the country, while in the capital city.

Special occasion food was available on-demand, all hours of the day.

One could eat food from days gone by as well as order food that was from other countries.

A wedding banquet featured total of 5 buffet lines.

A line of traditional Korean food, followed by seafood selection, fruit and salad, and dessert.

An hour and half allotted time was not enough to sample all the food and visit with relatives.

(in the wedding venues, scheduled are tightly set and each couple has 30 to 40 minutes to use the main hall and guests are directed to the dining hall afterwards, before the next couple starts their cycle of activities).

------------------------------------------------------------------------

The society had transformed from scarcity and inconvenient mode to one of utmost abundance and comfort.

During 50 years, the pace of growth and transformation has been remarkable.

Kudos to the people of Korea their achievements that borders on miracle.

As an aged observer, it seemed that in days of past, one was faced with daily challenges and inconvenience.

Lack of food and walk to nearly all places.

Now days, there are more food than the population 2 or 3 times can consume.

In addition, one has to look for ways to exercise, find a way to walk to places and rely on personal navigation skills rather than rely on electronic help.

------------------------------------------------------------------------

Not suggesting that those days were preferable to today.

Days of poverty, hunger and physical demands

But in some ways, discomfort, pain and hardship developed character and appreciation.

There must be ways to earn it in these Goldilocks days.

If you know of a way, please let me know, I need a reminder.

Provo,

July 2025
