---
title: "Reed J Irvine"
author: "DK"
date: "2025-08-11"
draft: yes
categories: [mentors]
---

# **IRVINE, Reed (John) 1922-2004**

*OBITUARY NOTICE—* See index for *CA* sketch: Born September 29, 1922, in [Salt Lake City](https://www.encyclopedia.com/places/united-states-and-canada/us-political-geography/salt-lake-city), UT; died of complications following a stroke November 16, 2004, in Rockville, MD. Consumer advocate, economist, and author. Irvine was the founder of the watchdog group Accuracy in Media (AIM). A graduate of the University of Utah, where he earned a B.A. in 1942, Irvine acted as an intelligence officer in the Pacific theater during [World War II](https://www.encyclopedia.com/history/modern-europe/wars-and-battles/world-war-ii). After the war, he returned to school, first at the University of Washington and then attending [Oxford University](https://www.encyclopedia.com/social-sciences-and-law/education/colleges-international/oxford-university) on a Fulbright scholarship. He graduated from Oxford in 1951 and was hired as an economist at the [Federal Reserve System](https://www.encyclopedia.com/social-sciences-and-law/economics-business-and-labor/money-banking-and-investment/federal-reserve) board of governors. From 1963 until 1977 he was international finance adviser for the Far East section. It was while working for the Federal Reserve that he got his idea to form AIM out of frustration with what he considered to be the slanted liberal perspective of the media. Founded in 1969, AIM often worked to get equal air time on television and space in newspapers for its more conservative views, and Irvine also wrote a syndicated column that was printed in about one hundred newspapers. The organization saw its most influential period during the years Ronald Reagan was president, declining somewhat in the 1990s as Irvine became increasingly preoccupied with investigating conspiracy theories, such as his belief that the crash of TWA Flight 800 was caused by a missile and that [White House](https://www.encyclopedia.com/places/united-states-and-canada/us-national-park-system/white-house) deputy counsel Vincent W. Foster Jr. might have actually been murdered, not a victim of suicide, in 1993. In 1985, Irvine started a venture similar to AIM, known as Accuracy in Academia, but its conservative agenda and desire to wield influence over academic freedoms found fewer sympathizers. Irvine remained chair of AIM until 2003, when he retired as chairman emeritus. He was the author of *Media Mischief and Misdeeds* (1984).

-   from Encyclopedia.com, <https://www.encyclopedia.com/arts/educational-magazines/irvine-reed-john-1922-2004>

---

Accuracy in Academia (AIA)’s founder, Reed Irvine, died November 16, 2004 at the age of 82. Born in 1922, he served his country in World War II as a marine. He really never stopped serving his country.

He started Accuracy in Media (AIM), AIA’s parent organization, in 1969, to scrutinize the then-dominant old media at a time when few questioned its reporting. From the time he retired as a Federal Reserve Board economist in the 1970s until late last year, when he suffered a serious heart attack, he worked for AIM full-time.

It is fair to say that the so-called new media—Fox News, talk radio and even internet blogs—that prove the reporting of the venerable CBS News and company to be inaccurate are rushing through a door that Reed Irvine opened when he started going head-to-head with media heavyweights such as then-Washington Post editor Ben Bradlee.

Reed Irvine started AIA in 1985 because he saw that too many professors were using classrooms the way that too many reporters used newsrooms—to influence events rather than provide actual accounts of the past and present. He served as chairman of AIA until his death.

Since the 1980s, his standards have guided AIA. In his late seventies, he went toe to toe with demonstrators who attempted to disrupt an AIA conference at Columbia University in New York City.

When I first came to AIA last year, I read an e-mail that Reed forwarded around the office. He answered one of AIM’s critics by writing, “Show me one thing that we have written that is inaccurate.” No one could.

On October 22, 1985, Izvestiya, the state-run newspaper in the then-still existent Soviet Union, ran an article on the founding of Accuracy in Academia (AIA). Of all of the press coverage that AIA has received in its history, the Izvestiya write-up is arguably the most historically significant. Entitled ‘The Hunt For Freethinkers,’ the piece took aim at the then-infant group’s purpose.

“By the look of things, henceforth students, with the start of their activities, will take out fountain pens and tape recorders,” Izvestiya predicted. “Teachers at universities are quivering with fear,” the Soviet press organ reported. “They tremble at the utterance of each word.”

“For who knows?,” Izvestiya asked rhetorically. “Are the students taking notes on their lectures for their own purposes, or are they listening for the purpose of reporting what the teacher says to the ultra-right organization, Accuracy in Academia?”

Izvestiya normally confined itself to attacking U. S. government policies and American society in general. Leveling a front-page broadside at a small non-profit group represented somewhat of an editorial departure for the journal. The attention Izvestiya devoted to AIA, then, gave the watchdog group quite a distinction.

“The reactionary newspaper, The Washington Times, crows over the report that Accuracy in Academia, which has only existed for a few days, already has gathered voluntary informants on 110 university campuses throughout the United States,” Izvestiya noted.

“At the call of their spiritual mentor, worshippers and apprentices of McCarthy hunt for teachers who have the courage to adhere to liberal convictions,” according to Izvestiya. The McCarthy that Izvestiya refers to is the late Sen. Joseph R. McCarthy, R-WI, famous for his investigations of communists in U. S. government jobs.

“By such measures, these teachers are labeled ‘Marxists,’ which in contemporary America is pregnant with the most serious consequences,” Izvestiya asserted. “For example, political science professor Bertell Ollman knows this from personal experience for he dared admit that he was actually on the side of Marxism. Solely because of that he was not allowed to compete to fill a position at the University of Maryland.”

Six years after the Izvestiya article appeared, the Soviet Union itself imploded and the Cold War ended. This year, AIA celebrates 19 years of life and is still in business. Izvestiya is still in business too, although under new management. And by the way, so is Bertell Ollman. A professor of politics at New York University, he teaches ‘Socialist Theory’ for undergraduates and ‘Communism’ and ‘Methods of Political and Social Analysis’ at the graduate level.

Because professors such as Ollman, and their understudies, are still in business, teaching the history of the Cold War from the Evil Empire’s perspective, AIA continues its work, as our founder would have wanted us to.

**Accuracy in Academia founder, Reed Irvine,\
died November 16, 2004 at the age of 82.\
His legacy as a true advocate of democracy lives on.**

Reed Irvine, R. I. P.\
by: Malcolm A. Kline, November 17, 2004
