---
title: "Guides and Limits"
author: "DK"
date: "2025-07-27"
draft: yes
categories: [limits]
---

I have never met my grandfather, on both sides of the family.

My maternal grandfather passed away from acute appendicitis in his early 30s, 17 years before I was born.

My paternal grandfather became a statistic of the Korean War. He is one of the ones not accounted for. Although many believe he went north with his eldest son. Last time he was with the family was 12 years before my birth.

Consequently, both of my grandmothers and the young family lived as a refugee and without a place to call home.

------------------------------------------------------------------------

Main role of fathers is to set limits and to show how to live within that boundary or constraint.

My father and mother's family are mirror images.

My father became de facto head of the household with his older brother and his father missing during the War. He had 3 younger brothers and a sister

My mother was the oldest, she had a sister that remained in North, due to bombings she was not able to join the family. There were daughter and son that perished. So mother and the 5th child is significant. There were 2 other sisters and an uncle.

Both families survived physically without fathers.

Emotionally there were scars from lingering, slow-defeating habits

Smoking tobacco and drinking alcohol.

These are entry drugs.

Leads to gambling and eventually abandonment and destroyer of home.

My father put an end to it, he was iconolast.

Can one over come? Yes but much easier with father present.
