---
title: "Mr. Bojangles"
author: "DK"
date: "2025-09-10"
draft: yes
categories: [nostalgia]
---

I knew a man Bojangles and he danced for you in worn out shoes\
Silver hair, a ragged shirt and baggy pants, the old soft shoe\
He jumped so high, he jumped so high\
Then he'd lightly touched down

Mr. Bojangles\
Mr. Bojangles\
Mr. Bojangles\
Dance

I met him in a cell in New Orleans I was down and out\
He looked to me to be the eyes of age as he spoke right out\
He talked of life, he talked of life\
He lightly slapped his leg instead

He said the name Bojangles and he danced a lick across the cell\
He grabbed his pants for a better stance he jumped so high\
He clicked his heels\
He let go a laugh, he let go a laugh\
Shook back his clothes all around

Mr. Bojangles\
Mr. Bojangles\
Mr. Bojangles\
Dance

He's danced for those at minstrel shows\
And county fairs throughout the South\
He spoke with tears of 15 years\
How his dog and him they traveled about\
His dog up and died, he up and died\
After 20 years he still grieves

He said "I dance now at every chance in honky-tonks for drinks and tips\
But most of the time I spend behind these county bars 'cause I drink a bit"\
He shook his head and as he shook his head\
I heard someone ask, "Please?

Mr. Bojangles\
Mr. Bojangles\
Mr. Bojangles\
Dance

I knew a man "Bojangles" and he'd dance for you\
In worn out shoes\
Silver hair, baggy pants, and ragged shirt\
The old Soft Shoe\
He jumped so high, he jumped so high\
And then he'd lightly touch down

Mr. Bojangles\
Mr. Bojangles\
Mr. Bojangles\
Dance

---

I beg your pardon, mama, what did you say?\
My mind was drifting off on Martinique Bay\
It's not that I'm not interested, you see\
Augusta, Georgia is just no place to be

I think Jamaican in the moonlight\
Sandy beaches, drinking rum every night\
We got no money, mama, but we can go\
We'll split the difference, go to Coconut Grove

Keep on talking, mama, I can hear\
Your voice, it tickles down inside of my ear\
I feel a tropical vacation this year\
Might be the answer to this hillbilly fear

I think Jamaican in the moonlight\
Sandy beaches, drinking rum every night\
We got no money, mama, but we can go\
We'll split the difference, go to Coconut Grove

Voila! An American Dream\
Well, we can travel girl, without any means\
When it's as easy as closing your eyes\
And dream Jamaica is a big neon sign

Just keep talking, mama, I like that sound\
It goes so easy with that rain falling down\
I think a tropical vacation this year\
Might be the answer to this hillbilly fear

Voila! An American Dream\
Yeah, we can travel, girl, without any means\
When it's as easy as closing your eyes\
And dream Jamaica is a big neon sign

Just think Jamaican in the moonlight\
Sandy beaches, drinking rum every night\
We got no money, mama, but we can go\
We'll split the difference, go to Coconut Grove

---

If there's one thing in my life that's missing\
It's the time that I spend alone\
Sailing on the cool and bright clear water

There's lots of those friendly people\
They're showing me ways to go\
But I never want to lose their inspiration

Time for a cool change\
I know that it's time for a cool change\
And now that my life is so prearranged\
I know that it's time for a cool change

Well, I was born in the sign of water\
And it's there that I feel my best\
The albatross and the whales, they are my brothers

It's kind of a special feeling\
When you're out on the sea alone\
Staring at the full moon like a lover

Time for a cool change\
I know that it's time for a cool change\
Now that my life is so prearranged\
I know that it's time for a cool change

I've never been romantic\
And sometimes I don't care\
I know it may sound selfish\
But let me breathe the air\
Yeah, yeah\
Let me breathe the air

If there's one thing in my life that's missing\
It's the time that I spend alone\
Sailing on the cool and bright clear water

It's kind of a special feeling\
Out on the sea alone\
Staring at the full moon like a lover

Time for a cool change\
I know that it's time for a cool change\
Now that my life is so prearranged\
I know that it's time for a cool, cool, cool change

It's time, it's time, it's time, it's time\
For a cool, cool change\
(Time for a cool change)\
Ooh, I know it's time for a cool, cool change\
(Time for a cool change)\
Now that my life is so prearranged\
Well, I know, I know, I know, I know\
(Time for a cool change)\
It's time for a cool change\
Yes, it is, yes, it is, yes, it is\
You know it's time for a cool change
