---
title: "Dutch Approach"
author: "DK"
date: "2026-01-25"
draft: yes
categories: [limits, freedom]
---

The journey ended in Osaka (大阪).

After 650 kilometers of walking from Tokyo—guitar strapped to his back, his feet that endured bouts of blisters due to rain soaked shoes—a young Dutch traveler finally met his friends.

He had kept the trek a secret until the moment he arrived. When he revealed that he hadn't taken the Shinkansen, but had instead traced the historical Tokaido ( 東海道) path on foot, his friends reacted with a mix of shock and envy.

One friend captured their sentiment:

> *"Holland guys... they always do stuff like that!"*

------------------------------------------------------------------------

10 years ago, I combined a visit to my sister and her husband who was working in Toulouse with a business trip to Venlo, Netherlands.

I let my contact, Pieter van der Wal, know that I arrived in France.^[There is an apocryphal story about Pieter, who is about average Dutch person, 6'4" and very fit. Once he visited a factory that the Utah contingent visited.  The host group was curious as to how much alcohol westerners can consume, since very few visitors from Utah drank.  It was said that Pieter drank a copious amounts of beer and sake and didn't even register and continued to interact.  Or There’s an apocryphal story about Pieter, a fit, 6'4" Dutchman. During a factory visit, our hosts—unused to the Utah contingent's sobriety—decided to test his limits. Despite a mountain of beer and sake, Pieter didn't flinch, continuing to interact with total clarity while the hosts looked on in awe.]

He suggested that I take inter-city trains to Netherlands via overnight trains through Paris, Antwerp and Rotterdam.

A distance of nearly 1200km and taking 15 hours of travel time.

This was based on and continuation of our previous rail travel discussions

He went on his honeymoon to Switzerland on a train. A 800km journey and 12 hours.

I would tell him about the 600km journey from Singapore's Tanjong Pagar Station to Wakauf Bahru Station in Kelantan region of eastern Malaysia peninsula.

I held ace on that discussion.

The Tokyo to Sapporo journey was a 1200km trip that took 16 hours before the Shinkansen implementation.

Flying from point A to point B was not of interest to either one of us.

------------------------------------------------------------------------

## The Korean Approach

When I worked in Gumi, Korea, the company canteen provided 3 meals a day

Meals were finished in matter of minutes and most people either smoked, drank coffee or played 족구.

Though I haven't had Korean military training, I imagined the company ran like a military garrison.

Everyone understood their roles, don't step outside its bounds and keep working at the task at hand.

And prevailing mode was 빨리빠리, hurry-up.

Get things done and move on to the next project.

Although I didn't grow up in Korea, I catch myself thinking in that mode from time to time.

> What is the consensus view of how Koreans function as a group and as individuals?

But I also see the meaning in the Dutch-Approach.

Take things slow, see things for yourself, establish your own set of rules on how things are or the way it should be.

My current thinking is that the meal and the discussion is just as important as the activity that follows or replaces it.

When it comes to travel, the slower is better.

Especially if one can carry one's own burden and see and interact with nature as did Eddie van der Meer.

Keeping our journeys and travel secret since the benefit or the growth is personal, whether it is made public or not.
