<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="DK">
<meta name="dcterms.date" content="2025-10-09">

<title>Kyrgyzstan Visitor – Selected Thoughts</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-29e2c20b02301cfff04dc8050bf30c7e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-1322888c997fad56b0b4d776d35cf542.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Selected Thoughts</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Kyrgyzstan Visitor</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">koreans</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>DK </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 9, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>The neighborhood male group threw a party.</p>
<p>It was husband and wife event.</p>
<p>Wife wasn’t able to go.</p>
<p>I went</p>
<p>It was a dinner followed by presentation on early prophet, J Smith</p>
<p><img src="images/101178.jpeg" class="img-fluid"></p>
<p>Noticed a gentlemen that didn’t look like he was from this area.</p>
<p>He was from Kyrgyzstan.</p>
<p>Asked if he knew of Koreans, he said yes.</p>
<p>I didn’t know how Koreans got to Central Asia.</p>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 66%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Country</th>
<th>Approximate Number of Ethnic Koreans / Koreans</th>
<th>Source / Year</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td><strong>Kazakhstan</strong></td>
<td>~ <strong>120,686</strong></td>
<td>National Statistics Bureau of Kazakhstan, as of <strong>2025</strong>. <a href="https://en.orda.kz/kazakhstans-largest-ethnic-groups-updated-figures-released-6214/?utm_source=chatgpt.com" alt="https://en.orda.kz/kazakhstans-largest-ethnic-groups-updated-figures-released-6214/?utm_source=chatgpt.com"><u>Orda.kz</u></a></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 71%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Uzbekistan</strong></td>
<td>~ <strong>174,242</strong></td>
<td>From a recent ethnic composition breakdown; “Koreans – 174.2 thousand people”</td>
</tr>
</tbody>
</table>
<section id="estimated-koryo-saram-by-country-best-available-figures" class="level2">
<h2 class="anchored" data-anchor-id="estimated-koryo-saram-by-country-best-available-figures">Estimated Koryo-saram by country (best available figures)</h2>
<blockquote class="blockquote">
<p><strong>Summary total (rounded): ~ 500,000 Koryo-saram across former Soviet states.</strong> <a href="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com" alt="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com"><u>Wikipedia</u></a></p>
</blockquote>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Country</th>
<th>Approx. population (figure)</th>
<th>Source / note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Uzbekistan</strong></td>
<td><strong>~174,200</strong></td>
<td>Wikipedia / Koryo-saram (summary figure; commonly cited 2021 estimate). Recent academic work documents a substantial decline from ~220k (1990s) to ~180k (2014), with continued out-migration to S. Korea. <a href="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com" alt="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com"><u>Wikipedia+1</u></a></td>
</tr>
<tr class="even">
<td><strong>Kazakhstan</strong></td>
<td><strong>~118,450 – 120,686</strong></td>
<td>Multiple sources report ~118k (2021 series) and ~120k (2025 est. series for ethnic Koreans in Kazakhstan). See Kazakhstan ethnic-groups tables and MOFA historical numbers. <a href="https://en.wikipedia.org/wiki/Ethnic_groups_in_Kazakhstan?utm_source=chatgpt.com" alt="https://en.wikipedia.org/wiki/Ethnic_groups_in_Kazakhstan?utm_source=chatgpt.com"><u>Wikipedia+1</u></a></td>
</tr>
<tr class="odd">
<td><strong>Russia</strong></td>
<td><strong>87,819</strong> (2021 census)</td>
<td>Russian 2021 census reported 87,819 Koreans. Note: earlier censuses (2002/2010) reported higher counts; differences reflect migration, undercounting, and census methodology. <a href="https://en.wikipedia.org/wiki/2021_Russian_census?utm_source=chatgpt.com" alt="https://en.wikipedia.org/wiki/2021_Russian_census?utm_source=chatgpt.com"><u>Wikipedia+1</u></a></td>
</tr>
<tr class="even">
<td><strong>Kyrgyzstan</strong></td>
<td><strong>~17,094</strong></td>
<td>Figure commonly cited in regional studies and summaries (2021 series). <a href="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com" alt="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com"><u>Wikipedia+1</u></a></td>
</tr>
<tr class="odd">
<td><strong>Ukraine</strong></td>
<td><strong>~12,700 – 13,524</strong> (official older censuses / MOFA)</td>
<td>Ukraine’s 2001 census: 12,711. South Korean MOFA and other sources list a 2020s estimate ~13.5k (some estimates and reports give higher, up to ~30k, due to differing definitions and pre-war population flux). <a href="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com" alt="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com"><u>Wikipedia+1</u></a></td>
</tr>
<tr class="even">
<td><strong>Tajikistan</strong></td>
<td><strong>~634</strong></td>
<td>National census (2010) and aggregated sources report very small Korean communities (hundreds). <a href="https://www.researchgate.net/publication/302379282_Koreans_in_Kazakhstan_Uzbekistan_and_Russia?utm_source=chatgpt.com" alt="https://www.researchgate.net/publication/302379282_Koreans_in_Kazakhstan_Uzbekistan_and_Russia?utm_source=chatgpt.com"><u>ResearchGate+1</u></a></td>
</tr>
<tr class="odd">
<td><strong>Turkmenistan</strong></td>
<td><strong>~400</strong> (small community)</td>
<td>Very small numbers reported in aggregated demographic sources. <a href="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com" alt="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com"><u>Wikipedia</u></a></td>
</tr>
<tr class="even">
<td><strong>Belarus, Moldova, Baltic states, Caucasus</strong></td>
<td><strong>dozens → low thousands</strong></td>
<td>Small Koryo-saram communities scattered across these states (country counts often &lt;1,000). <a href="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com" alt="https://en.wikipedia.org/wiki/Koryo-saram?utm_source=chatgpt.com"><u>Wikipedia</u></a></td>
</tr>
</tbody>
</table>
<hr>
<p><a href="https://www.youtube.com/watch?v=qKOIWFszPJI" class="uri">https://www.youtube.com/watch?v=qKOIWFszPJI</a></p>
<p>In 1863, at the edge of Asia,</p>
<p>13 Korean families crossed from Korea into Russia</p>
<p>in search of a better life.</p>
<p>At that time, Korea, under the rule of Joseon Dynasty</p>
<p>was going through hard times.</p>
<p>Drought, famine, social inequality, and the exploitation of peasants</p>
<p>by the ruling elite turned the lives of hundreds</p>
<p>of thousands of peasants into a living hell.</p>
<p>Until the 1900s, there were multiple waves of Korean peasants crossing into Russia</p>
<p>and settling in various parts of Primorsky Krai, mainly in the city of Vladivostok.</p>
<p>They engaged in farming,</p>
<p>fishing, and small-scale trade, contributing to the regional economy.</p>
<p>Additionally, a considerable number of Korean immigrants</p>
<p>worked in the Russian railroad industry as laborers.</p>
<p>The Koreans were initially welcomed in the Russian Far East,</p>
<p>where they were seen as hardworking and valuable settlers</p>
<p>for developing this sparsely populated region.</p>
<p>This land offered them opportunities, including abundant farmland,</p>
<p>which the Koreans quickly utilized.</p>
<p>In 1905, the</p>
<p>Russo-Japanese War resulted in a Japanese victory.</p>
<p>Five years later, in 1910, the Japanese army officially annexed</p>
<p>Korea as a colony, sparking another wave of Korean migration.</p>
<p>In Russia, the Korean population grew significantly,</p>
<p>eventually forming a large community in the country.</p>
<p>These Koreans came to be known as Koryo Saram,</p>
<p>which literally translates to “Korea person”.</p>
<p>“Koryo” is a historical name for Korea and “Saram” means person in the Korean language.</p>
<p>Pretty straightforward right?</p>
<p>From this point on to maintain a consistent tone, I will use the term</p>
<p>Koryo Saram to refer to these Koreans.</p>
<p>In 1917, the Koryo Saram community in Russia faced another major challenge.</p>
<p>Can you guess what it was?</p>
<p>Yes, the Bolshevik revolution.</p>
<p>This shift in the country’s political landscape began</p>
<p>with the goal of uniting all ethnic groups and nationalities of the Soviet Union</p>
<p>under the ideals of justice, equality, peace and harmony.</p>
<p>Slogans like “Land to the peasants” and “Equal rights for all workers”</p>
<p>sparked immense excitement among the Koryo Saram.</p>
<p>Considering the hardships they had endured in Korea,</p>
<p>this new state seemed to offer them a dream.</p>
<p>The integration of the Koryo Saram into the Soviet Union was relatively smooth.</p>
<p>In the early years, they actively and willingly participated</p>
<p>in the Communist Party and joined the Soviet institutions.</p>
<p>This period also marked a renaissance of Korean culture within the Soviet Union.</p>
<p>A newspaper was printed in the Korean language, and Korean schools</p>
<p>and cultural institutions were established across the Russian Far East.</p>
<p>This allowed the growing Koryo Saram</p>
<p>population in the country to maintain their native language, which is</p>
<p>perhaps the most important cultural pillar of any ethnic group.</p>
<p>In 1863, when the first Koryo Saram settled in the Russian Far East,</p>
<p>their population was estimated at 13 families or around 100 people.</p>
<p>Just seven decades later, by the 1930s, this population had grown</p>
<p>to approximately 180,000 people, a massive increase.</p>
<p>The 1930s, however, were not kind to the Koryo Saram.</p>
<p>First, Joseph Stalin began consolidating absolute power within the Soviet Union.</p>
<p>Although he had held power since 1922,</p>
<p>the early 1930s marked a period when he gained full control of the state</p>
<p>without opposition.</p>
<p>Additionally, in 1931, Japan occupied Manchuria, the northeastern part of China.</p>
<p>This event increased tensions between the Soviet Union and Japan,</p>
<p>leading to frequent border clashes between Soviet and Japanese troops.</p>
<p>Six years later, in 1937, Japan invaded China,</p>
<p>and the specter of war between Japan and the Soviet Union loomed large.</p>
<p>Stalin, known for his extreme paranoia, grew increasingly fearful</p>
<p>of a potential Japanese attack on the Russian Far East.</p>
<p>His paranoia extended to the 180,000 Koryo Saram living in the region.</p>
<p>Despite the fact that Koreans had been subjugated by Japan for years</p>
<p>and had actively resisted Japanese forces, even fighting in partizan detachments,</p>
<p>Stalin viewed the Koryo-Saram</p>
<p>as potential Japanese spies and enemy collaborators.</p>
<p>In September 1937, as winter approached, Stalin ordered the forced relocation</p>
<p>of all Koryo Saram from the Russian Far East to Central Asia.</p>
<p>This marked the beginning of a tragic chapter for the Koryo Saram people.</p>
<p>They were given less than three days to gather their belongings before</p>
<p>being forced to leave their homes.</p>
<p>Families were packed into overcrowded trains and transported</p>
<p>in mass to areas primarily in Uzbekistan and Kazakhstan.</p>
<p>The conditions in the wagons were appalling.</p>
<p>There was barely any food, and elders, women and children died in large numbers.</p>
<p>Those who perished during the journey were thrown out of the wagons</p>
<p>and their bodies abandoned to rot in the desolate steps of Central Asia.</p>
<p>Koreans traditionally believe that</p>
<p>if a person lacks a proper funeral, their spirits may become a “gwisin” (ghost).</p>
<p>Gwisin are often depicted as wandering spirits, tied to the location of their death</p>
<p>or to the family they were connected to, sometimes causing misfortune.</p>
<p>Because of this belief, the Koryo Saram often refer to these trains</p>
<p>as ghost trains, believing that the restless spirits of the Koreans</p>
<p>who did not survive the journey still roam the steps of Central Asia.</p>
<p>The journey lasted over a month and spanned 6500km.</p>
<p>Approximately 100,000 Koryo Saram were relocated to Kazakhstan,</p>
<p>and 80,000 to Uzbekistan.</p>
<p>Just as they had when they crossed from Korea to Russia,</p>
<p>they were forced to start over again.</p>
<p>The Koryo Saram were scattered across the vast region.</p>
<p>Some managed to settle in abandoned houses, while others found work on farms.</p>
<p>However, the real tragedy struck the Koryo Saram, who were left</p>
<p>with no resources to survive on the harsh outskirts of the Kazakh town of Ushtobe.</p>
<p>The landscape, composed of steppes with scarce resources,</p>
<p>forced many to dig holes in the ground to survive the winter.</p>
<p>Over two years, thousands of Koryo Saram died</p>
<p>due to starvation, exposure and disease.</p>
<p>The Koryo Saram, known for their resilience,</p>
<p>managed to get back on their feet</p>
<p>within two years of their arrival in Uzbekistan and Kazakhstan.</p>
<p>Despite losing thousands of their kin and enduring immense hardships,</p>
<p>they built homes and schools</p>
<p>for themselves and found work in the agricultural sector.</p>
<p>At that time, the steps of Kazakhstan were dry with low soil fertility.</p>
<p>However, the Koryo Saram achieved the seemingly impossible,</p>
<p>transforming these barren lands into thriving farms.</p>
<p>Things appeared to be improving, and it seemed that after all the calamities,</p>
<p>the Koryo Saram had found a new home where they could grow and prosper.</p>
<p>Unfortunately, this hope was short lived.</p>
<p>A new directive from Stalin ordered the systematic closure of Korean language</p>
<p>schools and publications</p>
<p>as a part of broader efforts to assimilate the Koryo Saram population</p>
<p>and suppress any potential cultural or political dissent.</p>
<p>In addition, Stalin imposed a travel ban on the Koryo Saram,</p>
<p>preventing them from leaving the farms where they worked.</p>
<p>This period marked the beginning of the decline</p>
<p>of the Korean language among the Koryo Saram people.</p>
<p>Before we move further, I want to take a moment to delve deeper</p>
<p>into the Korean language spoken by the Koryo Saram.</p>
<p>Since most of the Koreans who migrated to Russia came from the Hamgyong province,</p>
<p>now a part of North Korea, they spoke the Hamgyong dialect of Korean.</p>
<p>For many years, until the banning of Korean schools</p>
<p>and the Korean language within the Soviet Union in the early 1940s,</p>
<p>the Koryo Saram preserved their native tongue.</p>
<p>Over time, however, the Korean spoken by the Koryo Saram evolved into a distinct dialect</p>
<p>known as Koryo-mar.</p>
<p>This dialect absorbed a significant number of loanwords</p>
<p>and grammatical influences from Russian and Central Asian languages</p>
<p>due to the Koryo Saram’s assimilation into local cultures</p>
<p>and the multilingual environment they lived in.</p>
<p>While Korean traditionally uses the Hangul script,</p>
<p>Koryo-mar speakers historically lacked consistent use of Hangul.</p>
<p>Instead, they often adopted the Cyrillic alphabet for practical</p>
<p>purposes, particularly in Soviet contexts.</p>
<p>Now let’s jump back into our timeline.</p>
<p>We’ll return to Koryo-mar in more detail later.</p>
<p>It’s 1953, and guess what happened?</p>
<p>Yes, Stalin is dead.</p>
<p>With his death, the Koryo Saram gained more freedom to choose</p>
<p>where to live, what to do, and what kind of education to pursue.</p>
<p>While they were not completely free, their lives improved a lot more compared</p>
<p>to the Stalin era.</p>
<p>This year marked the beginning of a mass migration of Koryo Saram</p>
<p>into major cities.</p>
<p>They enrolled in colleges, pursued diverse careers,</p>
<p>and began to emerge across various layers of Soviet society.</p>
<p>Among all the Koryo Saram who built successful careers</p>
<p>in the Soviet Union, the most famous is often considered to be Viktor Tsoi.</p>
<p>He was the founder of Kino, the most iconic Soviet rock band.</p>
<p>Despite his untimely passing at the young age of 28,</p>
<p>Viktor Tsoi left behind an enduring legacy.</p>
<p>Today, he is remembered as one of the USSR’s greatest music legends.</p>
<p>His music became a unifying force for Soviet youth, transcending</p>
<p>regional and cultural differences across the country.</p>
<p>Ironically, Stalin’s death further negatively</p>
<p>impacted the preservation of the Korean language.</p>
<p>Until this point, despite numerous obstacles such as the banning of Korean language</p>
<p>education and the closure of Korean schools,</p>
<p>the language had managed to survive within the Koryo Saram community.</p>
<p>This survival was largely because, since the earliest years of Korean</p>
<p>immigration to Russia, the community</p>
<p>had always stuck together, living side by side.</p>
<p>This close-knit</p>
<p>way of life enabled the language to be passed down to younger generations.</p>
<p>However, with Stalin’s death and the newfound freedom for Koryo Saram</p>
<p>to choose their own paths,</p>
<p>they dispersed to different parts of the country.</p>
<p>As a result, Russian became increasingly relevant to their daily</p>
<p>lives, further eroding the use of the Korean language.</p>
<p>I found some pretty interesting data from previous Soviet censuses</p>
<p>that display the Koryo Saram population in different Soviet republics.</p>
<p>As we discussed a few moments ago, Kazakhstan and Uzbekistan had the largest</p>
<p>Koryo Saram populations by far.</p>
<p>Here, especially in the early years,</p>
<p>you can see that the number of Koryo Saram in other republics was quite low.</p>
<p>However, particularly after the 1959 census, we can observe</p>
<p>a sharp increase in their population across other Soviet republics.</p>
<p>I also found this quite interesting map</p>
<p>from 1976 showing the ethnic composition of the Soviet Union.</p>
<p>If we zoom in to the far eastern lands of the country,</p>
<p>we see no Korean presence on the map except for this tiny spot.</p>
<p>However, if we move west,</p>
<p>here in southern Kazakhstan, we see areas with a Korean majority.</p>
<p>Additionally, in Uzbekistan,</p>
<p>we can observe Korean presence in certain places.</p>
<p>This is truly an amazing map, which I believe we should explore in</p>
<p>a separate video.</p>
<p>All right,</p>
<p>years passed and in 1991, the Soviet Union collapsed.</p>
<p>The Koryo Saram people mainly stayed in Kazakhstan and Uzbekistan.</p>
<p>However, a considerable number of them also immigrated to countries like Russia,</p>
<p>Ukraine, Kyrgyzstan, Tajikistan, South Korea and the US.</p>
<p>Today, although pinpointing an exact number</p>
<p>for the Koryo Saram population worldwide is quite difficult,</p>
<p>it is estimated that their population is around 500,000.</p>
<p>To break down this number,</p>
<p>let’s look at the population of Koryo Saram and Korean language speakers by country.</p>
<p>In Russia,</p>
<p>according to the 2021 census, the Korean population is 87,819.</p>
<p>In total, 26,662 people speak Korean in the country,</p>
<p>17,631 of whom named Korean as their native language.</p>
<p>However, keep in mind that these numbers include not only the Koryo Saram people,</p>
<p>but also the descendants of North Korean immigrants who came to the Soviet Union</p>
<p>after the Korean War, and Sakhalin Koreans who were brought to Russia’s Sakhalin Island</p>
<p>as laborers following the Japanese invasion of the island.</p>
<p>In Kazakhstan, the 2021 census recorded the Korean population in the country as 118,450.</p>
<p>Out of 19.1 million Kazakh citizens documented in the census, 59,397 of them spoke Korean.</p>
<p>However, it is important to note that 48,303 Korean speakers</p>
<p>out of the 59,397 identified as Koreans.</p>
<p>The rest of the 11,094 Korean speakers</p>
<p>were mostly registered as Kazakh, Russian, Uzbek, and Uyghur.</p>
<p>When it comes to Uzbekistan,</p>
<p>unfortunately we don’t have detailed census data since the last national</p>
<p>population census was conducted in 1989 during the Soviet era.</p>
<p>However, the current estimates place</p>
<p>the Korean population in the country at around 174,000.</p>
<p>The Korean speaking population is estimated to be between 20 to 35,000.</p>
<p>In Kyrgyzstan, the 2022 census shows</p>
<p>that there are 5900 Koreans in the country.</p>
<p>Unfortunately, I was not able to find data on the number of Korean speakers.</p>
<p>In Ukraine,</p>
<p>the last national census was conducted in</p>
<p>2001, recording 12,700 Koreans in the country.</p>
<p>However, since this date, the country has undergone significant changes,</p>
<p>resulting in millions of people leaving Ukraine.</p>
<p>Today, the population of Koreans and Korean speakers in Ukraine is unknown.</p>
<p>Another country with a considerable Koryo Saram diaspora is the United States.</p>
<p>I was not able to find any data about the number of Koryo Saram,</p>
<p>since there are not registered as a separate ethnic group.</p>
<p>Today, although their population in the U.S is estimated to be in the hundreds,</p>
<p>it seems that they have managed to build</p>
<p>a tight community for themselves, mainly in New York.</p>
<p>Here, you can find restaurants serving Koryo Saram food,</p>
<p>which is ultimately a fusion of Korean and Kazakh, Uzbek, Russian cuisines.</p>
<p>Also, the All Nations Baptist Church in Brooklyn has a Koryo Saram pastor.</p>
<p>This multi-ethnic church has a Russian-speaking congregation,</p>
<p>consisting of people from various post-Soviet countries.</p>
<p>All right,</p>
<p>we covered all the countries where the Koryo Saram</p>
<p>have immigrated in large numbers.</p>
<p>But what about South Korea?</p>
<p>Since 1991, around 100,000 Koryo Saram</p>
<p>have returned to South Korea via special visa programs.</p>
<p>However, some of them spoke Russian as their native language</p>
<p>and have had a hard time integrating into Korean society.</p>
<p>Today, especially in Incheon,</p>
<p>there are multiple neighborhoods inhabited by Koryo Saram.</p>
<p>Since a considerable percentage of the population speaks Russian here,</p>
<p>it is quite common to see signboards in Russian on the streets.</p>
<p>In this day and age, the Koryo Saram in Kazakhstan and Uzbekistan can</p>
<p>be considered among the most successful ethnic groups in terms of business.</p>
<p>They primarily work in banking, agriculture, housing,</p>
<p>communications, trade, construction, and transportation.</p>
<p>In addition, many Koryo Saram run small and medium sized businesses.</p>
<p>Undoubtedly, the city of Almaty and Kazakhstan is the center of Koryo Saram</p>
<p>culture in the world.</p>
<p>Here you will find several Korean culture centers, Korean language</p>
<p>schools, and a Korean theater where one can watch plays in Korean.</p>
<p>Additionally, as I was researching contemporary Koryo Saram media,</p>
<p>I stumbled upon the Koryo Ilbo newspaper, which is published weekly in Korean</p>
<p>and Russian in Almaty.</p>
<p>Back in the 1970s and 80s it had a circulation of around 40,000.</p>
<p>However, today this number is down to 1000 weekly.</p>
<p>Unfortunately, today, most Koryo Saram</p>
<p>people don’t speak Korean.</p>
<p>A large portion of the speakers are the elder members of the community.</p>
<p>As of 2025, there is some sort of linguistic revival of Korean</p>
<p>among the young Koryo Saram, especially in Kazakhstan and Uzbekistan.</p>
<p>However, this is not enough to stop the decline of Korean in the community.</p>
<p>Now, let’s hear how the variety of Korean that the Koryo Saram speak,</p>
<p>also known as the Koryo-mar dialect, sounds.</p>
<p>Unfortunately, I was not able to find subtitles for this video,</p>
<p>so if any Korean speakers are watching this, please let us know what this lovely</p>
<p>old lady is saying.</p>
<p>Today, the Koryo Saram remain</p>
<p>one of the most unique and interesting diasporas in the world.</p>
<p>Let alone rest of the world,</p>
<p>even most Koreans haven’t heard of this group.</p>
<p>The words of the famous Koryo Saram historian, German Kim</p>
<p>serve as a great testimony to the current state of Koryo Saram</p>
<p>in Central Asia.</p>
<p>To most people, ethnic revival means wearing</p>
<p>traditional clothing, eating Korean food, or learning the language.</p>
<p>But there is more to it than that.</p>
<p>It is not simply a matter of copying South Korean culture in a Central Asian context.</p>
<p>The Koryo Saram have a cultural tradition that has substantially diverged</p>
<p>from that of South Korea.</p>
<p>Over the past decades,</p>
<p>the Koryo Saram have lived together with peoples of various backgrounds</p>
<p>and cultures, including Russians, Europeans, and Central Asians.</p>
<p>These cultures are dramatically different from traditional Korean society,</p>
<p>and the Koryo Saram have substantially integrated</p>
<p>and acculturated, incorporating many aspects of these cultures into their own.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>