---
title: "Araki San"
author: "DK"
date: "2025-08-10"
draft: yes
categories: [intro]
---

私は、荒木　実（アラキ　ミノル）といいます。 荒木　誠（アラキ　マコト）の長男です。 Donald（ダンノ）の従兄弟（いとこ　first cousin） になります。 丁寧なお手紙をいただき、ありがとうございます。 とつぜんのことで驚きましたが、とても嬉しかったです。 ダンノや伯母（カチ）のことは、ずっと気になっていました。 父（誠）が、２０１１年に亡くなった後は、連絡できずに 時が過ぎてしまいました。 伯母（カチ）が亡くなったことは、2年ぐらい前に 義理の伯父（Ｒeedさん）のことをWEBで見てた時に知りました。 そして、ダンノの活躍の様子も、少しですが知ることができて、 嬉しかったです。 父が亡くなってからは、親戚との付き合いも殆どなくなり、 詳しくは、あまりわからないのですが、できる限り調べてみます。

ダンノが1970年ごろに日本に来たときの写真を添付してみました。 古い写真なのでかなりぼやけてます。 伯母の両隣が、父（誠）と叔母（ナホ）です。 ダンノと一緒に写っているのが私と姉の由紀子です。

また、連絡させていただきます。 アメリカに帰られたら、ダンノと奥様に宜しくお伝えください。

荒木　実

------------------------------------------------------------------------

저는 아라키 미노루(荒木 実)라고 합니다.\

아라키 마코토(荒木 誠)의 장남입니다.\

도날드(단노)의 사촌 형제(첫 사촌)입니다.

정성 어린 편지 잘 받았습니다.\

갑작스러운 연락에 놀랐지만, 매우 기뻤습니다.\

단노와 고모(카치) 이야기는 늘 마음에 두고 있었습니다.\

아버지(마코토)가 2011년에 돌아가신 후로는 연락하지 못했고\

시간만 흘러갔습니다.

고모(카치)가 돌아가셨다는 것은 약 2년 전에\

시아버지(리드 씨)에 대해 웹에서 볼 때 알게 되었습니다.\

그리고 단노가 활약하는 모습도 조금 알게 되어 기뻤습니다.

아버지가 돌아가신 이후로는 친척들과 거의 연락이 끊겨\

자세한 사정은 잘 모르지만, 가능한 한 조사해 보겠습니다.

단노가 1970년경 일본에 왔을 때 찍은 사진을 첨부했습니다.\

오래된 사진이라 꽤 흐릿합니다.\

고모 양옆에 있는 사람이 아버지(마코토)와 이모(나호)입니다.\

단노와 함께 찍힌 사람이 저와 누나 유키코입니다.

또 연락드리겠습니다.\

미국에 돌아가시면 단노와 부인께 안부 전해 주세요.

아라키 미노루 드림

------------------------------------------------------------------------

My name is Minoru Araki.\

I am the eldest son of Makoto Araki.\

I am Donald’s first cousin.

Thank you very much for your kind letter.\

I was surprised by the sudden contact, but I was very happy.\

I have always been concerned about Danno and my aunt Kachi.\

After my father (Makoto) passed away in 2011, I was unable to get in touch,\

and time just passed by.

I learned that Aunt Kachi passed away about two years ago\

when I was looking up information about my uncle-in-law Reed on the web.\

I was also happy to learn a little about Danno’s activities.

Since my father passed away, I have had very little contact with relatives,\

so I don’t know the details very well, but I will try to find out as much as I can.

I attached a photo from around 1970 when Danno came to Japan.\

It is an old photo, so it is quite blurry.\

On both sides of my aunt are my father (Makoto) and my aunt (Naho).\

In the photo with Danno are my sister Yukiko and me.

I will contact you again.\

When you return to America, please give my best regards to Danno and his wife.

Minoru Araki\
