---
title: "Goose Family"
author: "DK"
date: "2026-02-08"
draft: yes
categories: [family]
---

My father left Korea to work in Vietnam when he was 36.

I left US to work in Korea as an Expat, 2 months after turning 36.

We both worked for nearly 4 years in those roles.

With one significant difference.

My father worked alone in Đà Nẵng,Vietnam, a country at war.

Whereas my family joined me and lived in 대구, Korea while I worked at 구미 공단동 (Gumi Industrial Complex).

------------------------------------------------------------------------

Near the end of my assignment the company offered an attractive contract extension that would have kept us in Korea.

We chose to return to Utah, prioritizing the needs of our four children, all younger than a teenager.

Lately, I have found myself wondering:

> *What if we had stayed?*

Or, more economically based option,

> *What if we had split the family?*

------------------------------------------------------------------------

Koreans has coined the term, **기러기아빠 (Gireogi Appa or Goose Father)**

It refers to a Korean father who lives apart from his family, usually staying in Korea to work while his wife and children live overseas for the children’s education.

He supports them financially and sees them only occasionally. It is not an uncommon and emotionally demanding family arrangement shaped by Korea’s education and work culture.

He is the economic engine, and sacrifices are shared by the parents and the children for the good of the family, usually children, so goes the narrative.

------------------------------------------------------------------------

For Sister K and me, however, this was a total non-starter.

The idea of splitting the family never crossed our minds; had it been suggested, it would have been dismissed immediately.

My father didn’t have the option to take his family to a war zone.

He endured his isolation with a quiet, stoic strength because he didn't have a choice.

I, however, had a choice. And in making that choice, I’ve since asked questions about the family make-up:

-   What does it truly mean to keep a family together?
-   Is the role of a father merely to provide the "engine," or is there a part of his soul that cannot be replaced?
-   What are the invisible threads that keep a family intact across oceans, and conversely,
-   What are the silent wedges that can separate a family even when they share the same roof?

I have come to deeply appreciate the quiet endurance of the **기러기아빠**—men like my father. He endured so that we wouldn't have to.

------------------------------------------------------------------------

In his 1987 book, *A Conflict of Visions* Thomas Sowell wrote,

> "There are no solutions. There are only trade-offs."

He later clarified this further,

> "There are no solutions, only trade-offs; and you try to get the best trade-off you can get, that's all you can hope for."

------------------------------------------------------------------------

Over the generations, our family’s trade-offs have shifted. Our family traded my father's presence for our survival; I traded a lucrative contract for our connection.

My father’s time in Vietnam was a harsh trade: he gave up four years of presence and safety to provide us with an economic foundation.

Thirty-two years later, I faced my own version of that crossroads in Korea.

I am grateful for the sacrifices of my parents as well as those that continue to make sacrifices on behalf of future generations.
